class LocationNames:
    freeon = "Starting Area: Freeon"
    shades = "Caves Area: Shades"
    gil = "West Cliffs: Gil"
    starting_area_hill_chest = "Starting Area: Hill Chest"
    starting_area_below_water = "Starting Area: Below Water"
    starting_area_miniboss_reward = "Starting Area: Miniboss Reward"
    west_cliffs_floating_island_cave = "West Cliffs: Floating Island Cave"
    west_cliffs_hidden_door = "West Cliffs: Miniboss Reward"
    west_cliffs_underwater_room = "West Cliffs: Underwater Room"
    dark_area_in_pit = "Dark Area: In Pit"
    dark_area_by_light = "Dark Area: By Light"
    dark_area_miniboss_reward = "Dark Area: Miniboss Reward"
    cave_area_alcove_near_pool = "Cave Area: Alcove Near Pool"
    cave_area_in_pool = "Cave Area: In Pool"
    cave_area_past_lava_hopping = "Cave Area: Past Lava Hopping"
    faucet_area_miniboss_reward = "Faucet Area: Miniboss Reward"
    faucet_area_in_water_column = "Faucet Area: In Water Column"
    faucet_area_above_faucet_cave = "Faucet Area: Above Faucet Cave"
    snow_area_above_chimney = "Snow Area: Above Chimney"
    snow_area_miniboss_reward = "Snow Area: Miniboss Reward"
    lava_challenge_climbing_ice = "Lava Challenge: Climbing Ice"
    lava_challenge_miniboss_reward = "Lava Challenge: Miniboss Reward"
    east_vertical_shaft_hover_chest = "East Vertical Shaft: Hover Chest"
    east_vertical_shaft_by_long_drop = "East Vertical Shaft: By Long Drop"
    clouds_area_miniboss_reward = "Clouds Area: Miniboss Reward"
    clouds_area_entrance_chest = "Clouds Area: Entrance Chest"
    final_boss_corridor_chest = "Final Boss Corridor: Chest"


l = LocationNames()
